### PR TITLE
update pubspec

### PR DESCRIPTION
**Pull request by knottx**
update pubspec

### CODE REVIEW

**Comment by nikb7** [comment]
@pewiher can you merge this?

**Comment by nikb7** [comment]
Any update on this?

**Comment by ricardo-kowalski** [comment]
> Any update on this?

I also need this

**Comment by pewiher** [comment]
Hello, good afternoon, it is planned to release the new version no later than June 15, 2023.

**Comment by pewiher** [comment]
update version 0.0.10, thanks so much 🥇 :)

**Pull request closed without merging**
